export { addImportOrExport } from "./accumulateRenamesForImportedIdentifier.js";
export { addSingleFileReplacementsForRenames } from "./addSingleFileReplacementsForRenames.js";
export { autorenameIdentifierAndReferences } from "./autorenameIdentifierAndReferences.js";
export { NamespaceContext, ProjectContext } from "./Context.js";
export { getReplacementsForRenames } from "./getReplacementsForRenames.js";
export type { PackageExportRename, PackageExportRenames } from "./PackageExportRename.js";
export { processReplacements } from "./processReplacements.js";
export { replaceAllNamesInScope } from "./replaceAllNamesInScope.js";
export type { Replacement } from "./Replacement.js";
export type { Replacements } from "./Replacements.js";
export { ReplacementsWrapperForContext, SimpleReplacements } from "./ReplacementsWrapper.js";
