name: Publish Snapshot

on:
  workflow_run:
    workflows: Test
    branches: main
    types: completed

jobs:
  publish-snapshot:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: "pnpm"
          registry-url: "https://registry.npmjs.org"
      - name: Install Deps
        run: pnpm install
      - run: pnpm ci:publish-snapshot
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
